#!/bin/sh

# XDG Base Directory specification
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Shell configuration
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_STATE_HOME/history"
export HISTSIZE=100
export SAVEHIST=100

# Default applications
export EDITOR="nvim"
export TERMINAL="foot"
export BROWSER="firefox"
export FILE="lf"
export IMAGE="nsxiv"
export VIDEO="mpv"

# Program configs
export LESSHISTFILE="$XDG_STATE_HOME/less_history"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export TMUX_CONFIG_DIR="$XDG_CONFIG_HOME/tmux"
export TMUX_PLUGIN_MANAGER_PATH="$XDG_DATA_HOME/tmux/plugins"
