#!/bin/sh

# XDG Base Directory specification
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# Shell configuration
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_STATE_HOME/history"
export HISTSIZE=10000
export SAVEHIST=10000

# Default applications
export EDITOR="nvim"
export TERMINAL="foot"
export BROWSER="firefox"
export FILE="lf"
export IMAGE="nsxiv"
export VIDEO="mpv"

# Program configs
export LESSHISTFILE="$XDG_STATE_HOME/less_history"
